name: Node CI

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
      env:
        CI: true
    - name: Lint (code & styles)
      run: |
        npm run lint
      env:
        CI: true
    - name: Run tests
      run: |
        npm run test -- --ci --coverage
      env:
        CI: true
    - name: npm build (module)
      run: |
        npm run build
      env:
        CI: true
    - name: npm build (storybook)
      run: |
        npm run build-storybook
      env:
        CI: true
