name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build (module + storybook)
      run: |
        npm install
        npm run build
        npm run build-storybook
      env:
        CI: true
    - name: npm test and lint
      run: |
        npm run test -- --ci --coverage --coverageReporters=text-lcov | coveralls
        npm run lint
      env:
        CI: true
